Fix for new build
duckdblabs/substrait pull request #11
Opened 2022-11-02 16:30 UTC by samansmink

This seems to fix the issue I ran into where when building the extension from the DuckDB CI, it would fail.

2022-11-02 16:33 UTC, pdet requested changes
Hey Sam, just a small comment.

Thanks for fixing this!

2022-11-02 16:33 UTC, pdet commented on CMakeLists.txt
> +    add_subdirectory(arrow)
this should be substrait, no?

2022-11-02 16:36 UTC, samansmink commented on CMakeLists.txt
> +    add_subdirectory(arrow)
yea that probably works a lot better

2022-11-03 15:10 UTC, samansmink commented
I'll close this one for now as there's another issue with this that needs a bit more thought: duckdb currently looks for the extensions only in the root build dir of the extension. Since the new build system moves the extensions one folder down into a folder, currently duckdb scripts/ci do not find it.

we need to fix where out of tree extensions are expected to produce their libraries for the duckdb ci to find them.

2022-11-03 15:10 UTC, closed without merging